version: '3.8'
services:
  fbreaper-microservice:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - kafka
      - libretranslate
  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5000:5000"
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7687:7687"
      - "7474:7474"
